server:
  port: 8080

spring:
  application:
    name: clines-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clines}?currentSchema=public
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

