name: Maven Release

on:
  release:
    types: [ created ]

jobs:
  build-maven-docker-hub:
    uses: https://github.com/jnslabs/github-reusable-workflow-ci/.github/workflows/maven-release.yml
    secrets: inherit